name: CI/CD

on:
  push:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    steps:

      - uses: actions/checkout@v3
      - name: Docker Login

      - run: ./mvnw package
      - name: Maven Package







    
